//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCaisse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caisse
    {
        public Caisse()
        {
            this.Approvisionnements = new HashSet<Approvisionnement>();
            this.Decaissements = new HashSet<Decaissement>();
        }
    
        public int idCaisse { get; set; }
        public Nullable<int> somme { get; set; }
    
        public virtual ICollection<Approvisionnement> Approvisionnements { get; set; }
        public virtual ICollection<Decaissement> Decaissements { get; set; }
    }
}
