//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCaisse
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandeDecaissement
    {
        public DemandeDecaissement()
        {
            this.Decaissements = new HashSet<Decaissement>();
            this.PieceJointes = new HashSet<PieceJointe>();
        }
    
        public int idDemandeDecaissement { get; set; }
        public string motif { get; set; }
        public Nullable<int> montantDemande { get; set; }
        public Nullable<System.DateTime> dateDemande { get; set; }
        public Nullable<int> idTypeDemande { get; set; }
        public string statutDemande { get; set; }
        public Nullable<int> idEmploye { get; set; }
    
        public virtual ICollection<Decaissement> Decaissements { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual TypeDemande TypeDemande { get; set; }
        public virtual ICollection<PieceJointe> PieceJointes { get; set; }
    }
}
