//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCaisse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public Employe()
        {
            this.Approvisionnements = new HashSet<Approvisionnement>();
            this.Decaissements = new HashSet<Decaissement>();
            this.DemandeDecaissements = new HashSet<DemandeDecaissement>();
        }
    
        public int idEmploye { get; set; }
        public string nomEmploye { get; set; }
        public string prenomEmploye { get; set; }
        public string statut { get; set; }
        public Nullable<int> numeroTelephone { get; set; }
        public string mot_de_passe { get; set; }
        public Nullable<System.DateTime> derniereConnexion { get; set; }
        public string sexe { get; set; }
    
        public virtual ICollection<Approvisionnement> Approvisionnements { get; set; }
        public virtual ICollection<Decaissement> Decaissements { get; set; }
        public virtual ICollection<DemandeDecaissement> DemandeDecaissements { get; set; }
    }
}
