//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCaisse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_CaisseEntities : DbContext
    {
        public Gestion_CaisseEntities()
            : base("name=Gestion_CaisseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Approvisionnement> Approvisionnements { get; set; }
        public DbSet<Caisse> Caisses { get; set; }
        public DbSet<Decaissement> Decaissements { get; set; }
        public DbSet<Employe> Employes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<PieceJointe> PieceJointes { get; set; }
        public DbSet<TypeDemande> TypeDemandes { get; set; }
        public DbSet<DemandeDecaissement> DemandeDecaissements { get; set; }
    }
}
