//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCaisse
{
    using System;
    using System.Collections.Generic;
    
    public partial class PieceJointe
    {
        public int idPieceJointe { get; set; }
        public byte[] cheminFichier { get; set; }
        public Nullable<int> idDemandeDecaissement { get; set; }
    
        public virtual DemandeDecaissement DemandeDecaissement { get; set; }
    }
}
